#!/usr/bin/env python3
from __future__ import annotations

import argparse
import glob
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Tuple


@dataclass(frozen=True)
class CheckItem:
    phase: str
    category: str
    label: str
    patterns: Tuple[str, ...]
    mode: str = "all"  # all|any


CHECKS: List[CheckItem] = [
    CheckItem("phase1", "binaries", "run_serial source", ("apps/run_serial.cpp",)),
    CheckItem("phase1", "scripts", "phase1 runner", ("scripts/run_phase1_dev_benchmarks.sh",)),
    CheckItem("phase1", "scripts", "phase1 summary", ("scripts/summarize_phase1_dev.py",)),
    CheckItem("phase1", "results", "phase1 raw artifacts", ("results/raw/phase1_dev/*.csv",), mode="any"),
    CheckItem("phase1", "results", "phase1 summary table", ("results/tables/phase1_dev/*.csv",), mode="any"),
    CheckItem("phase1", "results", "phase1 graphs", ("results/graphs/phase1_dev/*",), mode="any"),
    CheckItem("phase2", "binaries", "run_parallel source", ("apps/run_parallel.cpp",)),
    CheckItem("phase2", "scripts", "phase2 runner", ("scripts/run_phase2_dev_benchmarks.sh",)),
    CheckItem("phase2", "scripts", "phase2 summary", ("scripts/summarize_phase2_dev.py",)),
    CheckItem("phase2", "scripts", "phase2 determinism", ("scripts/check_phase2_dev_determinism.py",)),
    CheckItem("phase2", "results", "phase2 raw artifacts", ("results/raw/phase2_dev/*.csv",), mode="any"),
    CheckItem("phase2", "results", "phase2 validation artifacts", ("results/raw/phase2_dev/validation/*.csv",), mode="any"),
    CheckItem("phase2", "results", "phase2 summary table", ("results/tables/phase2_dev/*.csv",), mode="any"),
    CheckItem("phase3", "binaries", "run_optimized source", ("apps/run_optimized.cpp",)),
    CheckItem("phase3", "scripts", "phase3 runner", ("scripts/run_phase3_dev_benchmarks.sh",)),
    CheckItem("phase3", "scripts", "phase3 summary", ("scripts/summarize_phase3_dev.py",)),
    CheckItem("phase3", "scripts", "phase3 determinism", ("scripts/check_phase3_dev_determinism.py",)),
    CheckItem("phase3", "scripts", "phase3 completeness", ("scripts/check_phase3_dev_completeness.py",)),
    CheckItem("phase3", "scripts", "phase3 baseline runner", ("scripts/run_phase3_baseline_benchmarks.sh",)),
    CheckItem("phase3", "results", "phase3 raw artifacts", ("results/raw/phase3_dev/*.csv",), mode="any"),
    CheckItem("phase3", "results", "phase3 validation artifacts", ("results/raw/phase3_dev/validation/*.csv",), mode="any"),
    CheckItem("phase3", "results", "phase3 summary table", ("results/tables/phase3_dev/*.csv",), mode="any"),
    CheckItem("phase3", "results", "phase3 memory artifacts", ("results/raw/phase3_dev/memory/*.csv",), mode="any"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit Phase 1/2/3 deliverables against source and artifact presence.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument(
        "--output",
        default="docs/review/PHASE_DELIVERABLE_AUDIT.md",
        help="Markdown report output path",
    )
    return parser.parse_args()


def resolve_matches(root: Path, pattern: str) -> List[str]:
    abs_pattern = str(root / pattern)
    out = [Path(p).relative_to(root).as_posix() for p in glob.glob(abs_pattern)]
    out.sort()
    return out


def evaluate_item(root: Path, item: CheckItem) -> Tuple[bool, List[List[str]]]:
    matched_by_pattern = [resolve_matches(root, pat) for pat in item.patterns]
    if item.mode == "all":
        ok = all(len(m) > 0 for m in matched_by_pattern)
    else:
        ok = any(len(m) > 0 for m in matched_by_pattern)
    return ok, matched_by_pattern


def first_n(items: Iterable[str], n: int = 3) -> str:
    seq = list(items)
    if not seq:
        return "-"
    if len(seq) <= n:
        return ", ".join(f"`{v}`" for v in seq)
    shown = ", ".join(f"`{v}`" for v in seq[:n])
    return f"{shown}, ... ({len(seq)} total)"


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    report_path = (root / args.output).resolve()
    report_path.parent.mkdir(parents=True, exist_ok=True)

    rows = []
    for item in CHECKS:
        ok, matches = evaluate_item(root, item)
        flattened = [m for group in matches for m in group]
        rows.append((item, ok, flattened))

    lines: List[str] = []
    lines.append("# Phase Deliverable Audit")
    lines.append("")
    lines.append("Auto-generated by `scripts/audit_phase_deliverables.py`.")
    lines.append("")
    lines.append("| Phase | Category | Deliverable Check | Status | Evidence |")
    lines.append("|---|---|---|---|---|")

    for item, ok, evidence in rows:
        status = "PASS" if ok else "MISSING"
        lines.append(
            f"| {item.phase} | {item.category} | {item.label} | {status} | {first_n(evidence)} |"
        )

    lines.append("")
    lines.append("## Summary")
    for phase in ("phase1", "phase2", "phase3"):
        phase_rows = [r for r in rows if r[0].phase == phase]
        passed = sum(1 for _, ok, _ in phase_rows if ok)
        lines.append(f"- `{phase}`: {passed}/{len(phase_rows)} checks passing")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[audit_phase_deliverables] wrote: {report_path}")
    for phase in ("phase1", "phase2", "phase3"):
        phase_rows = [r for r in rows if r[0].phase == phase]
        passed = sum(1 for _, ok, _ in phase_rows if ok)
        print(f"[audit_phase_deliverables] {phase}: {passed}/{len(phase_rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

