#!/usr/bin/env python3
from __future__ import annotations

import argparse
import glob
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple


@dataclass
class TokenCheck:
    line_no: int
    line_text: str
    token: str
    exists: bool
    matches: List[str]


TODO_FILES = (
    "docs/TODO_PHASE1.md",
    "docs/TODO_PHASE2.md",
    "docs/TODO_PHASE3.md",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit checked TODO items that reference file paths in backticks."
    )
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument(
        "--output",
        default="docs/review/TODO_EVIDENCE_AUDIT.md",
        help="Markdown report output path",
    )
    return parser.parse_args()


def candidate_token(token: str) -> bool:
    if token.startswith("http://") or token.startswith("https://"):
        return False
    if token.startswith("-") or token.startswith("--"):
        return False
    if " " in token:
        return False
    if token.endswith(")"):
        return False
    return "/" in token or token.startswith("results")


def resolve_token(root: Path, token: str) -> Tuple[bool, List[str]]:
    pattern = str(root / token)
    matches = [Path(p).relative_to(root).as_posix() for p in glob.glob(pattern)]
    matches.sort()
    return len(matches) > 0, matches


def collect_checks(root: Path, todo_path: Path) -> List[TokenCheck]:
    checks: List[TokenCheck] = []
    backtick_re = re.compile(r"`([^`]+)`")
    for idx, line in enumerate(todo_path.read_text(encoding="utf-8").splitlines(), start=1):
        if "- [x]" not in line:
            continue
        for token in backtick_re.findall(line):
            if not candidate_token(token):
                continue
            ok, matches = resolve_token(root, token)
            checks.append(
                TokenCheck(
                    line_no=idx,
                    line_text=line.strip(),
                    token=token,
                    exists=ok,
                    matches=matches,
                )
            )
    return checks


def summarize(checks: List[TokenCheck]) -> Tuple[int, int]:
    total = len(checks)
    passed = sum(1 for c in checks if c.exists)
    return passed, total


def format_evidence(matches: List[str]) -> str:
    if not matches:
        return "-"
    if len(matches) <= 3:
        return ", ".join(f"`{m}`" for m in matches)
    head = ", ".join(f"`{m}`" for m in matches[:3])
    return f"{head}, ... ({len(matches)} total)"


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    out_path = (root / args.output).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    by_file: Dict[str, List[TokenCheck]] = {}
    for rel in TODO_FILES:
        path = root / rel
        if path.is_file():
            by_file[rel] = collect_checks(root, path)
        else:
            by_file[rel] = []

    lines: List[str] = []
    lines.append("# TODO Evidence Audit")
    lines.append("")
    lines.append("Auto-generated by `scripts/audit_todo_evidence.py`.")
    lines.append("This checks only `- [x]` lines that include backticked path-like tokens.")
    lines.append("")

    for rel, checks in by_file.items():
        passed, total = summarize(checks)
        lines.append(f"## {rel}")
        lines.append("")
        lines.append(f"- Passing tokens: `{passed}/{total}`")
        missing = [c for c in checks if not c.exists]
        lines.append(f"- Missing tokens: `{len(missing)}`")
        lines.append("")
        if missing:
            lines.append("| Line | Token | Evidence | Checked Item |")
            lines.append("|---|---|---|---|")
            for item in missing:
                lines.append(
                    f"| {item.line_no} | `{item.token}` | {format_evidence(item.matches)} | {item.line_text} |"
                )
            lines.append("")

    lines.append("## Summary")
    for rel, checks in by_file.items():
        passed, total = summarize(checks)
        lines.append(f"- `{rel}`: {passed}/{total}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[audit_todo_evidence] wrote: {out_path}")
    for rel, checks in by_file.items():
        passed, total = summarize(checks)
        print(f"[audit_todo_evidence] {rel}: {passed}/{total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

