#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List

from plot_common import (
    add_common_figure_text,
    save_matplotlib_figure,
    utc_now_iso,
    write_chart_manifest,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate simple Phase 1 dev benchmark graphs."
    )
    parser.add_argument(
        "--summary-csv",
        default="results/tables/phase1_dev/phase1_dev_summary.csv",
        help="Input summary CSV generated by summarize_phase1_dev.py",
    )
    parser.add_argument(
        "--output-dir",
        default="results/graphs/phase1_dev",
        help="Directory to save graph images.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate summary dataset/scenario mapping without generating plots.",
    )
    parser.add_argument(
        "--allow-partial",
        action="store_true",
        help="Allow missing subset/scenario combinations and render partial graphs (default: fail fast).",
    )
    return parser.parse_args()


def load_rows(summary_csv: Path) -> List[Dict[str, str]]:
    if not summary_csv.is_file():
        raise SystemExit(f"Summary CSV not found: {summary_csv}")
    with summary_csv.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    if not rows:
        raise SystemExit(f"Summary CSV has no data rows: {summary_csv}")
    return rows


def sort_dataset_labels(labels: List[str]) -> List[str]:
    known_order = {
        "small": 1,
        "small_smoke": 2,
        "medium": 3,
        "large_dev": 4,
    }
    return sorted(labels, key=lambda x: (known_order.get(x, 999), x))


def scenario_display_name(query_type: str) -> str:
    words = query_type.replace("_", " ").split()
    return " ".join(w.capitalize() for w in words) if words else query_type


def main() -> int:
    args = parse_args()
    summary_csv = Path(args.summary_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(summary_csv)

    labels = sorted({r["dataset_label"] for r in rows})
    subset_order = sort_dataset_labels(labels)
    if not subset_order:
        raise SystemExit("No dataset_label values found in summary CSV.")

    query_types = sorted({r["query_type"] for r in rows})
    if "ingest_only" not in query_types:
        raise SystemExit("Summary CSV is missing required ingest_only rows.")

    scenario_names = [q for q in query_types if q != "ingest_only"]
    if not scenario_names:
        raise SystemExit("Summary CSV has no query scenarios beyond ingest_only.")

    if args.dry_run:
        print(f"[plot_phase1_dev] dataset_labels={subset_order}")
        print(f"[plot_phase1_dev] scenarios={scenario_names}")
        print(f"[plot_phase1_dev] output_dir={output_dir}")
        return 0

    try:
        import matplotlib.pyplot as plt
    except Exception as exc:  # pragma: no cover
        raise SystemExit(
            "matplotlib is required to generate Phase 1 graphs.\n"
            "Install with one of:\n"
            "  python3 -m pip install matplotlib\n"
            "  sudo apt-get install python3-matplotlib\n"
            "Or run with --dry-run to validate dataset/scenario mapping without plotting."
        ) from exc

    subset_labels = subset_order
    ingest_only_map: Dict[str, float] = {}
    total_only_map: Dict[str, float] = {}
    generated_utc = utc_now_iso()
    runs_values = sorted({r.get("runs", "").strip() for r in rows if r.get("runs", "").strip()})
    runs_text = ",".join(runs_values) if runs_values else "unknown"
    subtitle = f"Phase 1 Dev | subsets={','.join(subset_order)} | runs={runs_text}"

    scenario_means: Dict[str, List[float]] = {name: [] for name in scenario_names}

    for subset in subset_order:
        subset_rows = [r for r in rows if r["dataset_label"] == subset]

        ingest_row = next((r for r in subset_rows if r["query_type"] == "ingest_only"), None)
        if ingest_row is None:
            if args.allow_partial:
                ingest_only_map[subset] = math.nan
                total_only_map[subset] = math.nan
                continue
            raise SystemExit(f"Missing ingest_only row for dataset_label={subset}")
        ingest_only_map[subset] = float(ingest_row["ingest_mean_ms"])
        total_only_map[subset] = float(ingest_row["total_mean_ms"])

        for scenario in scenario_names:
            scenario_row = next((r for r in subset_rows if r["query_type"] == scenario), None)
            if scenario_row is None and not args.allow_partial:
                raise SystemExit(
                    f"Missing scenario row for dataset_label={subset}, query_type={scenario}. "
                    "Use --allow-partial to render partial charts."
                )
            scenario_means[scenario].append(
                float(scenario_row["query_mean_ms"]) if scenario_row is not None else math.nan
            )

    manifest_rows: List[Dict[str, str]] = []

    # Graph 1: ingest time vs subset size
    fig1, ax1 = plt.subplots(figsize=(8, 5))
    ax1.plot(
        subset_labels,
        [ingest_only_map[s] for s in subset_order],
        marker="o",
        linewidth=2,
        color="#1f77b4",
    )
    ax1.set_title("Ingest Mean Runtime vs Subset Size")
    ax1.set_xlabel("Subset Size")
    ax1.set_ylabel("Ingest Mean Runtime (ms)")
    ax1.grid(True, alpha=0.3)
    add_common_figure_text(
        fig1,
        ax1,
        subtitle=subtitle,
        what_tested="How ingest runtime scales with subset size (ingest_only rows).",
        source_summary=summary_csv,
        generated_utc=generated_utc,
    )
    fig1.tight_layout(rect=(0, 0.03, 1, 0.92))
    fig1_paths = save_matplotlib_figure(fig1, output_dir, "ingest_time_vs_subset_size", dpi=150)
    plt.close(fig1)
    for p in fig1_paths:
        manifest_rows.append(
            {
                "chart_id": "phase1_ingest_vs_subset",
                "file_path": str(p),
                "phase": "phase1",
                "what_tested": "Ingest runtime scaling by subset size.",
                "x_axis": "Subset Size",
                "y_axis": "Ingest Mean Runtime (ms)",
                "source_summary_csv": str(summary_csv),
                "generated_utc": generated_utc,
            }
        )

    # Graph 2: total runtime vs subset size (ingest-only scenario)
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    ax2.plot(
        subset_labels,
        [total_only_map[s] for s in subset_order],
        marker="o",
        linewidth=2,
        color="#ff7f0e",
    )
    ax2.set_title("Total Mean Runtime vs Subset Size (Ingest-Only)")
    ax2.set_xlabel("Subset Size")
    ax2.set_ylabel("Total Mean Runtime (ms)")
    ax2.grid(True, alpha=0.3)
    add_common_figure_text(
        fig2,
        ax2,
        subtitle=subtitle,
        what_tested="End-to-end ingest-only total runtime by subset size.",
        source_summary=summary_csv,
        generated_utc=generated_utc,
    )
    fig2.tight_layout(rect=(0, 0.03, 1, 0.92))
    fig2_paths = save_matplotlib_figure(fig2, output_dir, "total_runtime_vs_subset_size", dpi=150)
    plt.close(fig2)
    for p in fig2_paths:
        manifest_rows.append(
            {
                "chart_id": "phase1_total_ingest_only_vs_subset",
                "file_path": str(p),
                "phase": "phase1",
                "what_tested": "Total ingest-only runtime scaling by subset size.",
                "x_axis": "Subset Size",
                "y_axis": "Total Mean Runtime (ms)",
                "source_summary_csv": str(summary_csv),
                "generated_utc": generated_utc,
            }
        )

    # Graph 3: query runtime by scenario across subset sizes
    fig3, ax3 = plt.subplots(figsize=(10, 6))
    for scenario in scenario_names:
        display = scenario_display_name(scenario)
        ax3.plot(
            subset_labels,
            scenario_means[scenario],
            marker="o",
            linewidth=2,
            label=display,
        )
    ax3.set_title("Query Mean Runtime by Scenario and Subset Size")
    ax3.set_xlabel("Subset Size")
    ax3.set_ylabel("Query Mean Runtime (ms)")
    ax3.grid(True, alpha=0.3)
    ax3.legend(title="Scenario")
    add_common_figure_text(
        fig3,
        ax3,
        subtitle=subtitle,
        what_tested="Query runtime behavior by scenario across subset sizes.",
        source_summary=summary_csv,
        generated_utc=generated_utc,
    )
    fig3.tight_layout(rect=(0, 0.03, 1, 0.92))
    fig3_paths = save_matplotlib_figure(fig3, output_dir, "query_runtime_by_scenario", dpi=150)
    plt.close(fig3)
    for p in fig3_paths:
        manifest_rows.append(
            {
                "chart_id": "phase1_query_runtime_by_scenario",
                "file_path": str(p),
                "phase": "phase1",
                "what_tested": "Query runtime by scenario across subset sizes.",
                "x_axis": "Subset Size",
                "y_axis": "Query Mean Runtime (ms)",
                "source_summary_csv": str(summary_csv),
                "generated_utc": generated_utc,
            }
        )

    manifest_path = output_dir / "chart_manifest.csv"
    write_chart_manifest(manifest_path, manifest_rows)
    for row in manifest_rows:
        print(f"[plot_phase1_dev] wrote: {row['file_path']}")
    print(f"[plot_phase1_dev] wrote: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
