#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate simple Phase 1 dev benchmark graphs."
    )
    parser.add_argument(
        "--summary-csv",
        default="results/tables/phase1_dev/phase1_dev_summary.csv",
        help="Input summary CSV generated by summarize_phase1_dev.py",
    )
    parser.add_argument(
        "--output-dir",
        default="results/graphs/phase1_dev",
        help="Directory to save graph images.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate summary dataset/scenario mapping without generating plots.",
    )
    return parser.parse_args()


def load_rows(summary_csv: Path) -> List[Dict[str, str]]:
    if not summary_csv.is_file():
        raise SystemExit(f"Summary CSV not found: {summary_csv}")
    with summary_csv.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    if not rows:
        raise SystemExit(f"Summary CSV has no data rows: {summary_csv}")
    return rows


def sort_dataset_labels(labels: List[str]) -> List[str]:
    known_order = {
        "small": 1,
        "small_smoke": 2,
        "medium": 3,
        "large_dev": 4,
    }
    return sorted(labels, key=lambda x: (known_order.get(x, 999), x))


def scenario_display_name(query_type: str) -> str:
    words = query_type.replace("_", " ").split()
    return " ".join(w.capitalize() for w in words) if words else query_type


def main() -> int:
    args = parse_args()
    summary_csv = Path(args.summary_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(summary_csv)

    labels = sorted({r["dataset_label"] for r in rows})
    subset_order = sort_dataset_labels(labels)
    if not subset_order:
        raise SystemExit("No dataset_label values found in summary CSV.")

    query_types = sorted({r["query_type"] for r in rows})
    if "ingest_only" not in query_types:
        raise SystemExit("Summary CSV is missing required ingest_only rows.")

    scenario_names = [q for q in query_types if q != "ingest_only"]
    if not scenario_names:
        raise SystemExit("Summary CSV has no query scenarios beyond ingest_only.")

    if args.dry_run:
        print(f"[plot_phase1_dev] dataset_labels={subset_order}")
        print(f"[plot_phase1_dev] scenarios={scenario_names}")
        print(f"[plot_phase1_dev] output_dir={output_dir}")
        return 0

    try:
        import matplotlib.pyplot as plt
    except Exception as exc:  # pragma: no cover
        raise SystemExit(
            "matplotlib is required to generate Phase 1 graphs.\n"
            "Install with one of:\n"
            "  python3 -m pip install matplotlib\n"
            "  sudo apt-get install python3-matplotlib\n"
            "Or run with --dry-run to validate dataset/scenario mapping without plotting."
        ) from exc

    subset_labels = subset_order
    ingest_only_map: Dict[str, float] = {}
    total_only_map: Dict[str, float] = {}

    scenario_means: Dict[str, List[float]] = {name: [] for name in scenario_names}

    for subset in subset_order:
        subset_rows = [r for r in rows if r["dataset_label"] == subset]

        ingest_row = next((r for r in subset_rows if r["query_type"] == "ingest_only"), None)
        if ingest_row is None:
            raise SystemExit(f"Missing ingest_only row for dataset_label={subset}")
        ingest_only_map[subset] = float(ingest_row["ingest_mean_ms"])
        total_only_map[subset] = float(ingest_row["total_mean_ms"])

        for scenario in scenario_names:
            scenario_row = next((r for r in subset_rows if r["query_type"] == scenario), None)
            scenario_means[scenario].append(
                float(scenario_row["query_mean_ms"]) if scenario_row is not None else math.nan
            )

    # Graph 1: ingest time vs subset size
    fig1, ax1 = plt.subplots(figsize=(8, 5))
    ax1.plot(
        subset_labels,
        [ingest_only_map[s] for s in subset_order],
        marker="o",
        linewidth=2,
        color="#1f77b4",
    )
    ax1.set_title("Ingest Mean Runtime vs Subset Size")
    ax1.set_xlabel("Subset Size")
    ax1.set_ylabel("Ingest Mean Runtime (ms)")
    ax1.grid(True, alpha=0.3)
    fig1.tight_layout()
    fig1_path = output_dir / "ingest_time_vs_subset_size.png"
    fig1.savefig(fig1_path, dpi=150)
    plt.close(fig1)

    # Graph 2: total runtime vs subset size (ingest-only scenario)
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    ax2.plot(
        subset_labels,
        [total_only_map[s] for s in subset_order],
        marker="o",
        linewidth=2,
        color="#ff7f0e",
    )
    ax2.set_title("Total Mean Runtime vs Subset Size (Ingest-Only)")
    ax2.set_xlabel("Subset Size")
    ax2.set_ylabel("Total Mean Runtime (ms)")
    ax2.grid(True, alpha=0.3)
    fig2.tight_layout()
    fig2_path = output_dir / "total_runtime_vs_subset_size.png"
    fig2.savefig(fig2_path, dpi=150)
    plt.close(fig2)

    # Graph 3: query runtime by scenario across subset sizes
    fig3, ax3 = plt.subplots(figsize=(10, 6))
    for scenario in scenario_names:
        display = scenario_display_name(scenario)
        ax3.plot(
            subset_labels,
            scenario_means[scenario],
            marker="o",
            linewidth=2,
            label=display,
        )
    ax3.set_title("Query Mean Runtime by Scenario and Subset Size")
    ax3.set_xlabel("Subset Size")
    ax3.set_ylabel("Query Mean Runtime (ms)")
    ax3.grid(True, alpha=0.3)
    ax3.legend()
    fig3.tight_layout()
    fig3_path = output_dir / "query_runtime_by_scenario.png"
    fig3.savefig(fig3_path, dpi=150)
    plt.close(fig3)

    print(f"[plot_phase1_dev] wrote: {fig1_path}")
    print(f"[plot_phase1_dev] wrote: {fig2_path}")
    print(f"[plot_phase1_dev] wrote: {fig3_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
