#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize Phase 2 dev benchmark CSV batch outputs."
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to batch manifest CSV generated by run_phase2_dev_benchmarks.sh",
    )
    parser.add_argument(
        "--output-dir",
        default="results/tables/phase2_dev",
        help="Directory to write summary table(s).",
    )
    parser.add_argument(
        "--output-file",
        default="phase2_dev_summary.csv",
        help="Summary CSV output filename.",
    )
    return parser.parse_args()


def summarize(values: List[float]) -> Tuple[float, float, float, float, float]:
    mean_v = statistics.fmean(values)
    median_v = statistics.median(values)
    min_v = min(values)
    max_v = max(values)
    stddev_v = statistics.stdev(values) if len(values) >= 2 else 0.0
    return mean_v, median_v, min_v, max_v, stddev_v


def speedup(serial_mean_ms: float, candidate_mean_ms: float) -> float:
    if candidate_mean_ms <= 0:
        return math.nan
    return serial_mean_ms / candidate_mean_ms


def load_manifest_rows(path: Path) -> List[Dict[str, str]]:
    if not path.is_file():
        raise SystemExit(f"Manifest not found: {path}")
    with path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    if not rows:
        raise SystemExit(f"Manifest has no rows: {path}")
    return rows


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / args.output_file

    manifest_rows = load_manifest_rows(manifest_path)

    grouped: Dict[Tuple[str, str, str, str], Dict[str, List[float]]] = defaultdict(
        lambda: {
            "ingest_ms": [],
            "query_ms": [],
            "total_ms": [],
            "records_per_second": [],
            "rows_accepted": [],
            "result_count": [],
            "average_speed_mph": [],
            "average_travel_time_seconds": [],
            "serial_match": [],
        }
    )

    serial_means: Dict[Tuple[str, str], float] = {}

    for entry in manifest_rows:
        mode = entry["mode"].strip()
        subset_label = entry["subset_label"].strip()
        scenario_name = entry["scenario_name"].strip()
        output_csv = Path(entry["output_csv"])

        if not output_csv.is_file():
            raise SystemExit(f"Missing output CSV listed in manifest: {output_csv}")

        with output_csv.open("r", newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                thread_count = row["thread_count"].strip()
                key = (subset_label, scenario_name, mode, thread_count)

                ingest_ms = float(row["ingest_ms"])
                query_ms = float(row["query_ms"])
                total_ms = float(row["total_ms"])
                rows_accepted = float(row["rows_accepted"])
                rps = rows_accepted / (total_ms / 1000.0) if total_ms > 0 else math.nan

                grouped[key]["ingest_ms"].append(ingest_ms)
                grouped[key]["query_ms"].append(query_ms)
                grouped[key]["total_ms"].append(total_ms)
                grouped[key]["records_per_second"].append(rps)
                grouped[key]["rows_accepted"].append(rows_accepted)
                grouped[key]["result_count"].append(float(row["result_count"]))
                grouped[key]["average_speed_mph"].append(float(row["average_speed_mph"]))
                grouped[key]["average_travel_time_seconds"].append(
                    float(row["average_travel_time_seconds"])
                )
                grouped[key]["serial_match"].append(1.0 if row["serial_match"] == "true" else 0.0)

    # baseline serial means for speedup reference
    for (subset_label, scenario_name, mode, thread_count), metrics in grouped.items():
        if mode == "serial" and thread_count == "1":
            serial_means[(subset_label, scenario_name)] = statistics.fmean(metrics["query_ms"])

    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(
            [
                "subset_label",
                "scenario_name",
                "mode",
                "thread_count",
                "runs",
                "ingest_mean_ms",
                "ingest_median_ms",
                "ingest_min_ms",
                "ingest_max_ms",
                "ingest_stddev_ms",
                "query_mean_ms",
                "query_median_ms",
                "query_min_ms",
                "query_max_ms",
                "query_stddev_ms",
                "total_mean_ms",
                "total_median_ms",
                "total_min_ms",
                "total_max_ms",
                "total_stddev_ms",
                "records_per_second_mean",
                "serial_match_rate",
                "result_count_mean",
                "avg_speed_mean",
                "avg_travel_time_mean",
                "speedup_vs_serial_query",
            ]
        )

        for key in sorted(grouped.keys()):
            subset_label, scenario_name, mode, thread_count = key
            metrics = grouped[key]
            ingest_stats = summarize(metrics["ingest_ms"])
            query_stats = summarize(metrics["query_ms"])
            total_stats = summarize(metrics["total_ms"])
            rps_stats = summarize(metrics["records_per_second"])
            runs = len(metrics["query_ms"])
            serial_baseline = serial_means.get((subset_label, scenario_name), math.nan)
            sp = speedup(serial_baseline, query_stats[0]) if not math.isnan(serial_baseline) else math.nan

            row = [subset_label, scenario_name, mode, thread_count, runs]
            for stats in (ingest_stats, query_stats, total_stats):
                row.extend([f"{v:.6f}" for v in stats])
            row.append(f"{rps_stats[0]:.6f}")
            row.append(f"{statistics.fmean(metrics['serial_match']):.6f}")
            row.append(f"{statistics.fmean(metrics['result_count']):.6f}")
            row.append(f"{statistics.fmean(metrics['average_speed_mph']):.6f}")
            row.append(f"{statistics.fmean(metrics['average_travel_time_seconds']):.6f}")
            row.append(f"{sp:.6f}" if not math.isnan(sp) else "nan")
            writer.writerow(row)

    print(f"[summarize_phase2_dev] wrote summary: {out_path}")
    print(f"[summarize_phase2_dev] groups: {len(grouped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
